language: common-lisp
sudo: required

# install ros
install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

# test with prove
# script:
#   - ros -s prove -e '(or (prove:run :cl-patterns/tests) (uiop:quit -1))'

# test with fiveam
script:
  - ros -e "(ql:quickload :cl-patterns/tests)
            (uiop:quit (if (fiveam:run! 'cl-patterns/tests::cl-patterns-tests)
                           0 1))"

notifications:
  email: false
  webhooks:
    urls:
        - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGRlZmF1bHR4ciUzQW1hdHJpeC5vcmcvJTIxb2dUa3B4cmlRb25LZE5VRFZGJTNBbWF0cml4Lm9yZw"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
